// Code generated by avro/gen. DO NOT EDIT.
package models

// Message is a generated struct.
type Message struct {
	ID        string `avro:"id" json:"id" yaml:"Id"`
	Content   string `avro:"content" json:"content" yaml:"Content"`
	Timestamp int64  `avro:"timestamp" json:"timestamp" yaml:"Timestamp"`
}
